const defaultwords = [
  ["μπαρ", "bar"],
  ["ουζερί", "ouzo bar"],
  ["ταβέρνα", "tavern / taverna"],
  ["εστιατόριο", "restaurant"],
  ["ζαχαροπλαστείο", "pastry shop / pastry / patisserie"],
  ["καφετερία", "coffee shop / cafe"],
  ["πρωινό", "breakfast"],
  ["γεύμα", "lunch"],
  ["δείπνο / βραδινό", "dinner"],
  ["τρώω", "eat / I eat"],
  ["μενού", "menu"],
  ["φαγητό σε πακέτο", "takeout / take out / to go / to-go"],
  ["άλλο", "another / other"],
  ["κλείνω / να κλείσω", "reserve / I reserve (a table)"],
  ["για πόσα άτομα", "how many people / for how many people / how many / for how many"],
  ["κράτηση", "reservation"],
  ["λογαριασμός", "bill / check"],
];
