const defaultwords = [
  ["λίτρο", "liter"],
  ["μπουκάλι", "bottle"],
  ["ποτήρι", "glass"],
  ["γραμμάρια", "grams"],
  ["κιλό", "kilo / kilogram"],
  ["μισό", "half"],
  ["φέτα", "slice"],
  ["μερίδα", "portion"],
  ["κουτί", "box / can"],
  ["βάζο", "jar"],
  ["περισσότερο", "more"],
  ["λιγότερο", "less"],
  ["αρκετό", "enough"],
  ["διπλό", "double"],
];
