const defaultwords = [
  ["ναι", "yes"],
  ["όχι", "no"],
  ["ευχαριστώ", "thank you / thanks"],
  ["Αμερική", "America / USA"],
  ["αγγλικά", "English"],
  ["εντάξει", "OK / okay"],
  ["παρακαλώ", "please / you're welcome"],
  ["συγνώμη", "sorry / excuse me"],
  ["κύριε", "mister / sir / mr"],
  ["κυρία", "madam / mrs"],
  ["γεια σας / γεια σου", "hello / hi / bye / goodbye"],
  ["καλημέρα", "good morning"],
  ["καλησπέρα", "good afternoon / good evening"],
  ["καληνύχτα", "good night"],
  ["μιλάω", "speak / I speak"],
  ["τι κάνετε / κάνεις", "how are you"],
  ["πολύ καλά", "good / well / very well"],
];
