const defaultwords = [
  ["καφές", "coffee"],
  ["μπύρα", "beer"],
  ["ποτήρι", "glass"],
  ["γλυκό", "sweet / dessert"],
  ["χωρίς ζάχαρη", "without sugar / no sugar"],
  ["καφές φραπέ / φραπέ", "iced coffee / frappe"],
  ["καπουτσίνο", "cappuccino"],
  ["ούζο", "ouzo"],
  ["τσάι", "tea"],
  ["μπουκάλι", "bottle"],
  ["εμφιαλωμένο νερό", "water / bottled water / mineral water"],
  ["αεριούχο", "sparkling / sparkling water"],
  ["απλό", "still / still water"],
  ["ψωμί", "bread"],
  ["γιαούρτι", "yogurt"],
  ["τζατζίκι", "tzatziki"],
  ["μουσακάς", "moussaka"],
  ["ντολμαδάκια", "stuffed grape leaves"],
  ["σουβλάκι", "kebab / meat skewer"],
  ["ψάρι", "fish"],
  ["αβγά", "eggs"],
  ["λαχανικά", "vegetables / veggies"],
  ["κρασί", "wine"],
];
