const defaultwords = [
  ["διαβατήριο", "passport"],
  ["πορτοφόλι", "wallet"],
  ["κινητό", "cell phone / cellphone / mobile"],
  ["είναι", "is"],
  ["έχω", "have / I have"],
  ["με", "with"],
  ["χωρίς", "without"],
  ["μεγάλο", "big"],
  ["μικρό", "small"],
  ["ανοικτό", "open"],
  ["κλειστό", "closed"],
  ["σελφ σέρβις", "self-service / self service"],
  ["είσοδος", "entrance"],
  ["έξοδος", "exit"],
  ["ταμείο", "checkout / cashier"],
  ["άνδρων", "men / men's"],
  ["γυναίκων", "women / women's"],
  ["δεν λειτουργεί", "out of order / out of service"],
];
